version: '3'
services:
  app:
    env_file: ".env"
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "80:${PORT}"
    environment:
      - PORT=${PORT}
      - UPDATE_FREQUENCY=${UPDATE_FREQUENCY}
      - SERVICE_COMMISSION=${SERVICE_COMMISSION}
